const CREATE_TASK = 'CREATE_TASK';
const CREATE_TASK_SUCCESS = 'CREATE_TASK_SUCCESS';
const CREATE_TASK_FAIL = 'CREATE_TASK_FAIL';

const GET_TASKS = 'GET_TASKS';
const GET_TASKS_SUCCESS = 'GET_TASKS_SUCCESS';
const GET_TASKS_FAIL = 'GET_TASKS_FAIL';

export default {
    CREATE_TASK,
    CREATE_TASK_SUCCESS,
    CREATE_TASK_FAIL,

    GET_TASKS,
    GET_TASKS_SUCCESS,
    GET_TASKS_FAIL
}